name: CI Build and Test

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and test backend
        run: ./mvnw clean install
        working-directory: ./back
      - name: Test Report (Backend)
        uses: phoenix-actions/test-reporting@v8
        if: success() || failure()
        with:
          name: JUnit Tests (Backend)
          path: back/target/surefire-reports/TEST-*.xml
          reporter: java-junit
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-jacoco-report
          path: back/target/site/jacoco/

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./front
      - name: Build Frontend
        run: npm run build
        working-directory: ./front
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      - name: Test Frontend
        run: npm run test:prod
        working-directory: ./front
      - name: Upload Frontend Coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: front/coverage/bobapp/